export const ERROR_CODES = {
  GENERIC: {
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  },
  AUTH: {
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    SIGNUP_FAILED: 'SIGNUP_FAILED',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    GOOGLE_LOGIN_FAILED: 'GOOGLE_LOGIN_FAILED',
  },
  NETWORK: {
    CONNECTION_FAILED: 'CONNECTION_FAILED',
    TIMEOUT: 'TIMEOUT',
    SERVER_ERROR: 'SERVER_ERROR',
  },
  VALIDATION: {
    INVALID_INPUT: 'INVALID_INPUT',
    MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
    INVALID_FORMAT: 'INVALID_FORMAT',
  },
  HOUSE: {
    MAX_HOUSES_REACHED: 'MAX_HOUSES_REACHED',
  },
} as const;
